// Etching Design — SVG Vector Exporter
// Produces 1:1 scale SVG with exact mm units and viewBox.

export function generateSVG(geom, options = {}) {
  const {
    showDimensions = true,
    showOrientationMarks = true,
    showLabels = true,
  } = options;

  const pw = geom.plate.width;
  const ph = geom.plate.height;

  // In SVG, Y=0 is Top, whereas internal mm has Y=0 at Bottom.
  // Transform: ySvg = ph - (y + height)
  const toSvgY = (y, h = 0) => Number((ph - (y + h)).toFixed(4));

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${pw} ${ph}" width="${pw}mm" height="${ph}mm">
  <title>Etching Design - ${pw}x${ph}mm</title>
  <desc>Precision Etching Layout generated by 3M Instrument Logger</desc>

  <defs>
    <style>
      .plate-outline { fill: #f8fafc; stroke: #1e293b; stroke-width: 0.4; }
      .sample-body { fill: #ffffff; stroke: #0f172a; stroke-width: 0.25; }
      .separator-line { fill: rgba(239, 68, 68, 0.15); stroke: #ef4444; stroke-width: 0.15; stroke-dasharray: 1, 1; }
      .connector-line { fill: rgba(16, 185, 129, 0.15); stroke: #10b981; stroke-width: 0.15; stroke-dasharray: 1, 1; }
      .boundary-strip { fill: rgba(217, 70, 239, 0.2); stroke: #d946ef; stroke-width: 0.3; }
      .tab-shape { fill: #cbd5e1; stroke: #475569; stroke-width: 0.15; }
      .dim-line { stroke: #2563eb; stroke-width: 0.2; }
      .dim-text { font-family: "JetBrains Mono", monospace; font-size: 2px; fill: #2563eb; }
      .label-text { font-family: "JetBrains Mono", monospace; font-size: 2.2px; fill: #475569; }
      .orient-arrow { stroke: #f97316; stroke-width: 0.3; stroke-linecap: round; fill: none; }
    </style>
  </defs>

  <!-- Layer: PLATE -->
  <g id="Layer_Plate">
    <rect class="plate-outline" x="0" y="0" width="${pw}" height="${ph}"/>
    <!-- Alignment tooling holes -->
    <circle cx="3.5" cy="3.5" r="1.5" fill="#94a3b8" stroke="#475569" stroke-width="0.2"/>
    <circle cx="${(pw - 3.5).toFixed(3)}" cy="3.5" r="1.5" fill="#94a3b8" stroke="#475569" stroke-width="0.2"/>
    <circle cx="3.5" cy="${(ph - 3.5).toFixed(3)}" r="1.5" fill="#94a3b8" stroke="#475569" stroke-width="0.2"/>
    <circle cx="${(pw - 3.5).toFixed(3)}" cy="${(ph - 3.5).toFixed(3)}" r="1.5" fill="#94a3b8" stroke="#475569" stroke-width="0.2"/>
  </g>

  <!-- Layer: BOUNDARIES -->
  <g id="Layer_Boundaries">
`;

  (geom.boundaries || []).forEach(b => {
    svg += `    <rect class="boundary-strip" x="${b.x.toFixed(3)}" y="${toSvgY(b.y, b.height)}" width="${b.width.toFixed(3)}" height="${b.height.toFixed(3)}"/>\n`;
  });

  svg += `  </g>

  <!-- Layer: SEPARATORS -->
  <g id="Layer_Separators">
`;
  (geom.separators || []).forEach(sep => {
    svg += `    <rect class="separator-line" x="${sep.x.toFixed(3)}" y="${toSvgY(sep.y, sep.height)}" width="${sep.width.toFixed(3)}" height="${sep.height.toFixed(3)}"/>\n`;
  });
  svg += `  </g>

  <!-- Layer: CONNECTORS -->
  <g id="Layer_Connectors">
`;
  (geom.connectors || []).forEach(con => {
    svg += `    <rect class="connector-line" x="${con.x.toFixed(3)}" y="${toSvgY(con.y, con.height)}" width="${con.width.toFixed(3)}" height="${con.height.toFixed(3)}"/>\n`;
  });
  svg += `  </g>

  <!-- Layer: SAMPLES -->
  <g id="Layer_Samples">
`;

  (geom.samples || []).forEach(s => {
    const sy = toSvgY(s.y, s.height);
    const r = s.cornerRadius || 0;
    if (s.cornerType === 'chamfer' && r > 0) {
      const pts = [
        `${(s.x + r).toFixed(3)},${sy.toFixed(3)}`,
        `${(s.x + s.width - r).toFixed(3)},${sy.toFixed(3)}`,
        `${(s.x + s.width).toFixed(3)},${(sy + r).toFixed(3)}`,
        `${(s.x + s.width).toFixed(3)},${(sy + s.height - r).toFixed(3)}`,
        `${(s.x + s.width - r).toFixed(3)},${(sy + s.height).toFixed(3)}`,
        `${(s.x + r).toFixed(3)},${(sy + s.height).toFixed(3)}`,
        `${s.x.toFixed(3)},${(sy + s.height - r).toFixed(3)}`,
        `${s.x.toFixed(3)},${(sy + r).toFixed(3)}`,
      ].join(' ');
      svg += `    <polygon class="sample-body" id="${s.id}" points="${pts}"/>\n`;
    } else if (s.cornerType === 'fillet' && r > 0) {
      svg += `    <rect class="sample-body" id="${s.id}" x="${s.x.toFixed(3)}" y="${sy}" width="${s.width.toFixed(3)}" height="${s.height.toFixed(3)}" rx="${r.toFixed(3)}" ry="${r.toFixed(3)}"/>\n`;
    } else {
      svg += `    <rect class="sample-body" id="${s.id}" x="${s.x.toFixed(3)}" y="${sy}" width="${s.width.toFixed(3)}" height="${s.height.toFixed(3)}"/>\n`;
    }

    // Tabs
    if (s.tabs && s.tabs.length) {
      s.tabs.forEach(tab => {
        const ty = toSvgY(tab.y1, tab.width);
        const tw = tab.x2 - tab.x1;
        svg += `    <rect class="tab-shape" x="${tab.x1.toFixed(3)}" y="${ty}" width="${tw.toFixed(3)}" height="${tab.width.toFixed(3)}"/>\n`;
      });
    }

    // Orientation Marks
    if (showOrientationMarks) {
      const cx = s.x + s.width / 2;
      const cy = sy + s.height / 2;
      const arm = Math.min(s.width, s.height) * 0.25;

      if (s.direction === 'up') {
        svg += `    <path class="orient-arrow" d="M ${cx} ${cy + arm} L ${cx} ${cy - arm} M ${cx - arm * 0.4} ${cy - arm * 0.4} L ${cx} ${cy - arm} L ${cx + arm * 0.4} ${cy - arm * 0.4}"/>\n`;
      } else if (s.direction === 'down') {
        svg += `    <path class="orient-arrow" d="M ${cx} ${cy - arm} L ${cx} ${cy + arm} M ${cx - arm * 0.4} ${cy + arm * 0.4} L ${cx} ${cy + arm} L ${cx + arm * 0.4} ${cy + arm * 0.4}"/>\n`;
      } else if (s.direction === 'right') {
        svg += `    <path class="orient-arrow" d="M ${cx - arm} ${cy} L ${cx + arm} ${cy} M ${cx + arm * 0.4} ${cy - arm * 0.4} L ${cx + arm} ${cy} L ${cx + arm * 0.4} ${cy + arm * 0.4}"/>\n`;
      } else if (s.direction === 'left') {
        svg += `    <path class="orient-arrow" d="M ${cx + arm} ${cy} L ${cx - arm} ${cy} M ${cx - arm * 0.4} ${cy - arm * 0.4} L ${cx - arm} ${cy} L ${cx - arm * 0.4} ${cy + arm * 0.4}"/>\n`;
      }
    }
  });

  svg += `  </g>

  <!-- Layer: LABELS -->
  <g id="Layer_Labels">
`;
  if (showLabels) {
    svg += `    <text class="label-text" x="10" y="${(ph - 2.5).toFixed(3)}">3M ETCHING DESIGN | Plate: ${pw}×${ph}mm | Total Samples: ${geom.totalSamples}EA | Yield: ${geom.summary?.yieldPct || 0}%</text>\n`;
  }
  svg += `  </g>

  <!-- Layer: DIMENSIONS -->
  <g id="Layer_Dimensions">
`;
  if (showDimensions) {
    // Plate width dimension (top)
    svg += `    <line class="dim-line" x1="0" y1="4" x2="${pw}" y2="4"/>\n`;
    svg += `    <line class="dim-line" x1="0" y1="2" x2="0" y2="6"/>\n`;
    svg += `    <line class="dim-line" x1="${pw}" y1="2" x2="${pw}" y2="6"/>\n`;
    svg += `    <text class="dim-text" x="${(pw / 2).toFixed(3)}" y="3" text-anchor="middle">${pw} mm</text>\n`;

    // Plate height dimension (right)
    svg += `    <line class="dim-line" x1="${pw - 4}" y1="0" x2="${pw - 4}" y2="${ph}"/>\n`;
    svg += `    <line class="dim-line" x1="${pw - 6}" y1="0" x2="${pw - 2}" y2="0"/>\n`;
    svg += `    <line class="dim-line" x1="${pw - 6}" y1="${ph}" x2="${pw - 2}" y2="${ph}"/>\n`;
    svg += `    <text class="dim-text" x="${pw - 3}" y="${(ph / 2).toFixed(3)}" text-anchor="start">${ph} mm</text>\n`;
  }
  svg += `  </g>
</svg>`;

  return svg;
}
